# change application ID
#application: training-conference-app
application: yourappid
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /images
  static_dir: images

- url: /css
  static_dir: css

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /userprofile
  script: main.app

- url: /scheduleconference
  script: main.app

- url: /developer
  script: main.app

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest
